app/urls.py
from django.urls import path
from .views.graphy_views import *
from .views.tarefa_views import *
from .views.usuario_views import *
from .views.search_views import *
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('index_tarefas/', index_tarefas, name='index_tarefas'),
    path('listar_tarefas/', listar_tarefas, name='listar_tarefas'),
    path('cadastrar_tarefa/', cadastrar_tarefa, name='cadastrar_tarefa'),
    path('editar_tarefa/<int:id>', editar_tarefa, name='editar_tarefa'),
    path('remover_tarefa/<int:id>', remover_tarefa, name='remover_tarefa'),
    path('cadastrar_usuario/', cadastrar_usuario, name='cadastrar_usuario'),
    path('logar_usuario/', logar_usuario, name='logar_usuario'),
    path('deslogar_usuario/', deslogar_usuario, name='deslogar_usuario'),
    path('grid_plot/', grid_plot, name='grid_plot'),
    path('search/', search, name='search'),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)



gerenciador_tarefas/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls'))
]

app/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Tarefa(models.Model):
    PERECIBILIDADE_CHOICES = [
        ("A", "Alta"),
        ("N", "Normal"),
        ("B", "Baixa"),
    ]
    UNIDADE_CHOICES = [
        ("BOCA DO RIO", "BOCA DO RIO"),
        ("CENTRO", "CENTRO"),
        ("IMBUI", "IMBUI"),
        ("PITUBA", "PITUBA"),
    ]
    unidade = models.CharField(max_length=20, choices=UNIDADE_CHOICES, null=False, blank=False)
    fornecedor = models.CharField(max_length=40, null=False, blank=False)
    produto = models.CharField(max_length=40, null=False, blank=False)
    codigo_barra = models.BigIntegerField(null=False, blank=False)
    data_fabricacao = models.DateField(null=False, blank=False)
    data_validade = models.DateField(null=False, blank=False)
    custo_unidade = models.FloatField(null=False, blank=False)
    quant_compra = models.IntegerField(null=False, blank=False)
    preco_venda = models.FloatField(null=False, blank=False)
    quant_venda = models.IntegerField(null=False, blank=False)
    perecibilidade = models.CharField(max_length=1, choices=PERECIBILIDADE_CHOICES, null=False, blank=False)
    foto_produto = models.ImageField(upload_to='images/')
    usuario = models.ForeignKey(User, null=True, on_delete=models.CASCADE)

app/views/search_views.py
from django.contrib import messages
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.db.models import Q
from ..models import Tarefa

def search(request):
    if request.method == 'POST':
        srch = request.POST['srh']
        if srch:
            match = Tarefa.objects.filter(Q(fornecedor__icontains=srch)|
                    Q(produto__icontains=srch)
                    )
            if match:
                return render(request, "tarefas/search.html", {"sr": match})
            else:
                messages.error(request, 'no result found')
        else:
            return HttpResponseRedirect('/search/')
    return render(request, 'tarefas/search.html')

app/views/tarefa_views.py
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.shortcuts import render, redirect
from ..forms import TarefaForm
from ..entidades.tarefa import Tarefa
from ..services import tarefa_service
# Create your views here.

def index_tarefas(request):
    i_tarefas= tarefa_service.index_tarefas()
    return render(request, 'tarefas/index_tarefas.html', {"i_tarefas":i_tarefas})

@login_required()
def listar_tarefas(request):
    if request.method == 'GET':
        tarefas = tarefa_service.listar_tarefas(request.user)
    return render(request, 'tarefas/listar_tarefas.html', {"tarefas":tarefas})

@login_required()
def cadastrar_tarefa(request):
    if request.method == "POST":
        form_tarefa = TarefaForm(request.POST, request.FILES)
        if form_tarefa.is_valid():
            unidade = form_tarefa.cleaned_data["unidade"]
            fornecedor = form_tarefa.cleaned_data["fornecedor"]
            produto = form_tarefa.cleaned_data["produto"]
            codigo_barra = form_tarefa.cleaned_data["codigo_barra"]
            data_fabricacao = form_tarefa.cleaned_data["data_fabricacao"]
            data_validade = form_tarefa.cleaned_data["data_validade"]
            custo_unidade = form_tarefa.cleaned_data["custo_unidade"]
            quant_compra = form_tarefa.cleaned_data["quant_compra"]
            preco_venda = form_tarefa.cleaned_data["preco_venda"]
            quant_venda = form_tarefa.cleaned_data["quant_venda"]
            perecibilidade = form_tarefa.cleaned_data["perecibilidade"]
            foto_produto  = form_tarefa.cleaned_data["foto_produto"]
            tarefa_nova = Tarefa(unidade=unidade, fornecedor=fornecedor, produto=produto,
                                 codigo_barra=codigo_barra, data_fabricacao=data_fabricacao, data_validade= data_validade,
                                 custo_unidade=custo_unidade, quant_compra=quant_compra,  preco_venda=preco_venda,
                                 quant_venda=quant_venda, perecibilidade=perecibilidade, foto_produto=foto_produto,
                                 usuario=request.user)
            tarefa_service.cadastrar_tarefa(tarefa_nova)
            return redirect('listar_tarefas')
    else:
        form_tarefa = TarefaForm()
    return render(request, 'tarefas/form_tarefa.html', {"form_tarefa": form_tarefa})

@login_required()
def editar_tarefa(request, id):
    tarefa_bd = tarefa_service.listar_tarefa_id(id)
    if tarefa_bd.usuario != request.user:
        return HttpResponse("Não permitido")
    form_tarefa = TarefaForm(request.POST or None, instance=tarefa_bd)
    if form_tarefa.is_valid():
        unidade = form_tarefa.cleaned_data["unidade"]
        fornecedor = form_tarefa.cleaned_data["fornecedor"]
        produto = form_tarefa.cleaned_data["produto"]
        codigo_barra = form_tarefa.cleaned_data["codigo_barra"]
        data_fabricacao = form_tarefa.cleaned_data["data_fabricacao"]
        data_validade = form_tarefa.cleaned_data["data_validade"]
        custo_unidade = form_tarefa.cleaned_data["custo_unidade"]
        quant_compra = form_tarefa.cleaned_data["quant_compra"]
        preco_venda = form_tarefa.cleaned_data["preco_venda"]
        quant_venda = form_tarefa.cleaned_data["quant_venda"]
        perecibilidade = form_tarefa.cleaned_data["perecibilidade"]
        foto_produto = form_tarefa.cleaned_data["foto_produto"]
        tarefa_nova = Tarefa(unidade=unidade, fornecedor=fornecedor, produto=produto,
                             codigo_barra=codigo_barra, data_fabricacao=data_fabricacao, data_validade=data_validade,
                             custo_unidade=custo_unidade, quant_compra=quant_compra, preco_venda=preco_venda,
                             quant_venda=quant_venda, perecibilidade=perecibilidade, foto_produto=foto_produto,
                             usuario=request.user)
        tarefa_service.editar_tarefa(tarefa_bd, tarefa_nova)
        return redirect('listar_tarefas')
    return render(request, 'tarefas/form_tarefa.html', {"form_tarefa": form_tarefa})

@login_required()
def remover_tarefa(request, id):
    tarefa_bd = tarefa_service.listar_tarefa_id(id)
    if request.method == "POST":
        tarefa_service.remover_tarefa(tarefa_bd)
        return redirect('listar_tarefas')
    return render(request,'tarefas/confirma_exclusao.html', {'tarefa': tarefa_bd})










app/templates/tarefas/confirma_exclusao.html
{% extends 'baseg.html' %}

{% block conteudo %}
<div class="shadow-lg p-3 mb-5 bg-white rounded">
<div class="card mb-3">
    <div class="card-header">
       Tem certeza que deseja remover a tarefa?
        <a href="{% url 'listar_tarefas' %}"><button class="btn btn-primary" type="submit">Back</button></a>
    </div>
    <div class="card-body">
        <h5 class="card-title">{{ tarefa.unidade }}</h5>
        <p class="card-text">{{ tarefa.fornecedor }}</p>
        <hr>
        <form method="post">
            {% csrf_token %}
            <button class="btn btn-danger" type="submit">Remover</button>
        </form>
    </div>
</div>
</div>
{% endblock conteudo %}

{% block conteudoright %}
<div class="card-deck">
    <div class="card bg-primary">
        <div class="card-title">
            <p class="card-text">Aqui serão abordados os principas resultados empiricos sobre dados econômicos de relevância. </p>
            <a href="https://exame.com/" class="btn btn-primary btn-sm" target="_self">Exame</a>
        </div>
    </div>
</div>
<br>

<div class="card-deck">
    <div class="card bg-primary">
        <div class="card-title">
            <p class="card-text">São aqui colocados em disponibilidade, alguns dados, brutos e processados, tidos como exemplo em nosso trabalho</p>
            <a href="#" class="btn btn-primary btn-sm">Veja </a>
        </div>
    </div>
</div>
<br>
<div class="card-deck">
    <div class="card bg-primary">
        <div class="card-title">
            <p class="card-text">Aqui são colocados à disponibilidade nossos serviços</p>
            <a href="{% url 'logar_usuario' %}" class="btn btn-primary btn-sm">Fale Comigo</a>
        </div>
    </div>
</div>
<br>
<div class="card-deck">
        <p>Somos fadados às necessidades de contrapartida, amiúde, o quê, que faz da união voto de desvantagem.</p>
        <footer class="blockquote-footer">
            <small class="text-muted">
            Objeto de pensamento: <cite title="Source Title">Nazareth, Luis</cite>
            </small>
        </footer>
</div>
{% endblock conteudoright%}

app/templates/tarefas/form_tarefa.html
{% extends 'basef.html' %}
{% load meus_filtros %}

{% block conteudo %}
<div class="alert alert-primary" role="alert">
     <div class="row no-gutters">
          <div class="col-6 col-md-4">
             <div class="spinner-grow text-primary" role="status">
                <span class="sr-only">Loading...</span>
             </div>
          </div>
         <div class="col-12 col-sm-6 col-md-8">
             <h4>Lista</h4>
         </div>
     </div>
</div>

<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="form-group">
         {{ form_tarefa.unidade.errors}}
            <label>Unidade:</label>
         {{ form_tarefa.unidade|addclass:'form-control'}}
    </div>
    <div class="form-group">
         {{ form_tarefa.fornecedor.errors}}
            <label>Fornecedor:</label>
         {{ form_tarefa.fornecedor|addclass:'form-control'}}
    </div>
    <div class="form-group">
         {{ form_tarefa.produto.errors}}
            <label>Produto:</label>
         {{ form_tarefa.produto|addclass:'form-control'}}
    </div>
    <div class="form-group">
         {{ form_tarefa.codigo_barra.errors}}
            <label>Código de Barras:</label>
         {{ form_tarefa.codigo_barra|addclass:'form-control'}}
    </div>
    <div class="form-group">
         {{ form_tarefa.data_fabricacao.errors}}
            <label>Data de Fabricacao (mês/data/ano):</label>
         {{ form_tarefa.data_fabricacao|addclass:'form-control' }}
    </div>
    <div class="form-group">
         {{ form_tarefa.data_validade.errors}}
            <label>Data de Validade (mês/data/ano):</label>
         {{ form_tarefa.data_validade|addclass:'form-control'}}
    </div>
    <div class="form-group">
         {{ form_tarefa.custo_unidade.errors}}
            <label>Custo/Unidade</label>
         {{ form_tarefa.custo_unidade|addclass:'form-control'}}
    </div>
    <div class="form-group">
         {{ form_tarefa.quant_compra.errors}}
            <label>Quantidade/compra:</label>
         {{ form_tarefa.quant_compra|addclass:'form-control'}}
    </div>
    <div class="form-group">
         {{ form_tarefa.preco_venda.errors}}
            <label>Preco de Venda/unidade:</label>
         {{ form_tarefa.preco_venda |addclass:'form-control'}}
    </div>
    <div class="form-group">
         {{ form_tarefa.quant_venda.errors}}
            <label>Quantidade/venda:</label>
         {{ form_tarefa.quant_venda|addclass:'form-control'}}
    </div>
    <div class="form-group">
         {{ form_tarefa.perecibilidade.errors}}
            <label>Perecibilidade:</label>
         {{ form_tarefa.perecibilidade|addclass:'form-control'}}
    </div>
    <div class="form-group">
         {{ form_tarefa.foto_produto.errors}}
            <label>Foto do Produto:</label>
         {{ form_tarefa.foto_produto|addclass:'form-control'}}
    </div>
    <div>
        <input type="submit" class="btn btn-primary btn-sm" value="Enviar">
    </div>
</form>
{% endblock conteudo %}
{% block conteudoright %}
<div class="shadow-lg p-3 mb-5 bg-white rounded">
<div class="card-deck">
    <div class="card bg-primary">
        <div class="card-title">
        <h5 class="card-title">Mercado</h5>
        <p class="card-text">Aqui serão abordados os principas resultados empiricos sobre dados econômicos de relevância. </p>
        <a href="{% url 'grid_plot' %}" class="btn btn-primary btn-sm" target="_self">Resultados</a>
        </div>
    </div>
</div>
<br>
<div class="card-deck">
    <div class="card bg-primary">
        <div class="card-title">
        <h5 class="card-title">Produtos</h5>
        <p class="card-text">São aqui colocados em disponibilidade, alguns dados, brutos e processados, tidos como exemplo em nosso trabalho</p>
        <a href="#" class="btn btn-primary btn-sm">Veja </a>
        </div>
    </div>
</div>
<br>
<div class="card-deck">
    <div class="card bg-primary">
        <div class="card-title">
        <h5 class="card-title">Serviços</h5>
        <p class="card-text">Aqui são colocados à disponibilidade nossos serviços</p>
        <a href="{% url 'logar_usuario' %}" class="btn btn-primary btn-sm">Contate-nos</a>
        </div>
    </div>
</div>
<br>
<div class="card-deck">
        <p>Somos fadados às necessidades de contrapartida, amiúde, o quê, que faz da união voto de desvantagem.</p>
        <footer class="blockquote-footer">
            <small class="text-muted">
            Objeto de pensamento: <cite title="Source Title">Nazareth, Luis</cite>
            </small>
        </footer>
</div>
</div>
{% endblock conteudoright %}

app/templates/tarefas/graphy_tarefa.html
{% extends 'baseg.html' %}

{% block conteudo %}
<div class="alert alert-primary" role="alert">
     <div class="row no-gutters">
          <div class="col-6 col-md-4">
             <div class="spinner-grow text-primary" role="status">
                <span class="sr-only">Loading...</span>
             </div>
          </div>
         <div class="col-12 col-sm-6 col-md-8">
             <h4>Resultados</h4>
         </div>
     </div>
</div>
    {{ div|safe }}
    {{script|safe}}
{% endblock conteudo %}

{% block conteudoright %}
<div class="shadow-lg p-3 mb-5 bg-white rounded">
    <div class="card-deck">
        <div class="card bg-primary">
            <div class="card-title">
                <p class="card-text">Aqui serão abordados os principas resultados empiricos sobre dados econômicos de relevância. </p>
                <a href="https://exame.com/" class="btn btn-primary btn-sm" target="_self">Exame</a>
            </div>
        </div>
    </div>
    <br>
    <div class="card-deck">
        <div class="card bg-primary">
            <div class="card-title">
                <p class="card-text">São aqui colocados em disponibilidade, alguns dados, brutos e processados, tidos como exemplo em nosso trabalho</p>
                <a href="#" class="btn btn-primary btn-sm">Veja </a>
            </div>
        </div>
    </div>
    <br>
    <div class="card-deck">
        <div class="card bg-primary">
            <div class="card-title">
                <p class="card-text">Aqui são colocados à disponibilidade nossos serviços</p>
                <a href="{% url 'logar_usuario' %}" class="btn btn-primary btn-sm">Fale Comigo</a>
            </div>
        </div>
    </div>
    <br>
    <div class="card-deck">
        <p>Somos fadados às necessidades de contrapartida, amiúde, o quê, que faz da união voto de desvantagem.</p>
        <footer class="blockquote-footer">
            <small class="text-muted">
            Objeto de pensamento: <cite title="Source Title">Nazareth, Luis</cite>
            </small>
        </footer>
    </div>
</div>
{% endblock conteudoright%}

app/templates/tarefas/index_tarefas.html
{% extends 'baset.html' %}

{% block conteudo %}
{% for tarefa in i_tarefas %}
    <div class="card mb-3">
        <div class="card-header">
            {{ tarefa.get_perecibilidade_display }}
        </div>
        <div class="card-body">
            <div class="row">
                <div class="col-6 col-sm-4">
                    <div class="card-image">
                        <img src="{{ tarefa.foto_produto.url }}" class="img-responsive" style="width: 30%; float: left; margin-right: 10px;" />
                    </div>
                </div>
                <div class="col-6 col-sm-4">
                    <h5 class="card-title">{{ tarefa.produto }}</h5>
                    <p class="card-text">{{ tarefa.data_validade }}</p>
                </div>
            </div>
            <hr>
            <div class="shadow-lg p-3 mb-5 bg-white rounded">
                    <p class="card-date">{{tarefa.preco_venda}}</p>
            </div>
        </div>
    </div>
{% endfor %}
<div class="row">
    <div class="col-auto mr-auto">
        <a href="{% url 'logar_usuario' %}"><input type="button" class="btn btn-primary btn-sm" value="login"></a>
    </div>
    <div class="col-auto">
        <a href="{% url 'cadastrar_usuario' %}"><input type="button" class="btn btn-primary btn-sm" value="Cadastro"></a>
    </div>
    <div class="col-auto">
      <a href="{% url 'index_tarefas' %}"><input type="button" class="btn btn-primary btn-sm" value="Go to Up"></a>
    </div>
</div>
{% endblock conteudo %}


{% block conteudoright %}
<div class="shadow-lg p-3 mb-5 bg-white rounded">
    <div class="card-deck">
        <div class="card bg-primary">
            <div class="card-title">
                <h5 class="card-title">Mercado</h5>
                <p class="card-text">Aqui serão abordados os principas resultados empiricos sobre dados econômicos de relevância. </p>
                <a href="https://exame.com/" class="btn btn-primary btn-sm" target="_self">Exame</a>
            </div>
        </div>
    </div>
    <br>
    <div class="card-deck">
        <div class="card bg-primary">
            <div class="card-title">
                <h5 class="card-title">Produtos</h5>
                <p class="card-text">São aqui colocados em disponibilidade, alguns dados, brutos e processados, tidos como exemplo em nosso trabalho</p>
                <a href="{% url 'search' %}" class="btn btn-primary btn-sm">Veja </a>
            </div>
        </div>
    </div>
    <br>
    <div class="card-deck">
        <div class="card bg-primary">
            <div class="card-title">
                <h5 class="card-title">Serviços</h5>
                <p class="card-text">Aqui são colocados à disponibilidade nossos serviços</p>
                <a href="{% url 'logar_usuario' %}" class="btn btn-primary btn-sm">Fale Comigo</a>
            </div>
        </div>
    </div>
    <br>
    <div class="card-deck">
        <p>Somos fadados às necessidades de contrapartida, amiúde, o quê, que faz da união voto de desvantagem.</p>
        <footer class="blockquote-footer">
            <small class="text-muted">
            Objeto de pensamento: <cite title="Source Title">Nazareth, Luis</cite>
            </small>
        </footer>
    </div>
</div>
{% endblock conteudoright %}






app/templates/tarefas/listar_tarefas.html
{% extends 'basem.html' %}

{% block conteudo %}
<div class="alert alert-primary" role="alert">
     <div class="row no-gutters">
          <div class="col-6 col-md-4">
             <div class="spinner-grow text-primary" role="status">
                <span class="sr-only">Loading...</span>
             </div>
          </div>
         <div class="col-12 col-sm-6 col-md-8">
             <h4>Elementos</h4>
         </div>
     </div>
</div>


{% for tarefa in tarefas%}

<div class="card mb-3">
    <div class="card-header">
        {{ tarefa.get_perecibilidade_display }}
    </div>

    <div class="card-body">
        <div class="row">
            <div class="col-6 col-sm-4">
                <div class="card-image">
                    <img src="{{ tarefa.foto_produto.url }}" class="img-responsive" style="width: 30%; float: left; margin-right: 10px;" />
                </div>
            </div>
            <div class="col-6 col-sm-4">
                <h5 class="card-title">{{ tarefa.produto }}</h5>
                <p class="card-text">{{ tarefa.data_validade }}</p>
            </div>
        </div>

        <hr>
        <div class="shadow-lg p-3 mb-5 bg-white rounded">
            <div class="card-footer">
                <a href="{% url 'editar_tarefa' tarefa.id %}"><button type="button" class="btn btn-primary btn-sm">Editar</button></a>
                <a href="{% url 'remover_tarefa' tarefa.id %}"><button type="button" class="btn btn-primary btn-sm">Remover</button></a>
            </div>
        </div>
    </div>
</div>
{% endfor %}

<div class="row">
    <div class="col-auto mr-auto">
        <a href="{% url 'cadastrar_tarefa' %}"><input type="button" class="btn btn-primary btn-sm" value="Cadastrar Tarefa"></a>
    </div>
    <div class="col-auto">
        <a href="{% url 'listar_tarefas' %}"><input type="button" class="btn btn-primary btn-sm" value="Go to Up"></a>
    </div>
</div>
{% endblock conteudo%}

{% block conteudoright %}
<div class="shadow-lg p-3 mb-5 bg-white rounded">
    <div class="card-deck">
        <div class="card bg-primary">
            <div class="card-title">
                <h5 class="card-title">Mercado</h5>
                <p class="card-text">Aqui serão abordados os principas resultados empiricos sobre dados econômicos de relevância. </p>
                <a href="{% url 'grid_plot' %}" class="btn btn-primary btn-sm" target="_self">Resultados</a>
            </div>
        </div>
    </div>
    <br>
    <div class="card-deck">
        <div class="card bg-primary">
            <div class="card-title">
                <h5 class="card-title">Produtos</h5>
                <p class="card-text">São aqui colocados em disponibilidade, alguns dados, brutos e processados, tidos como exemplo em nosso trabalho</p>
                <a href="#" class="btn btn-primary btn-sm">Veja </a>
            </div>
        </div>
    </div>
    <br>
    <div class="card-deck">
        <div class="card bg-primary">
            <div class="card-title">
                <h5 class="card-title">Serviços</h5>
                <p class="card-text">Aqui são colocados à disponibilidade nossos serviços</p>
                <a href="{% url 'logar_usuario' %}" class="btn btn-primary btn-sm">Contate-nos</a>
            </div>
        </div>
    </div>
    <br>
    <div class="card-deck">
        <p>Somos fadados às necessidades de contrapartida, amiúde, o quê, que faz da união voto de desvantagem.</p>
        <footer class="blockquote-footer">
            <small class="text-muted">
            Objeto de pensamento: <cite title="Source Title">Nazareth, Luis</cite>
            </small>
        </footer>
    </div>
</div>
{% endblock conteudoright %}




app/templates/tarefas/search.html
{% extends 'bases.html' %}
{% load meus_filtros %}

{% block conteudo %}
<h1>Search</h1>
<form method="post" action="/search/">
  {% csrf_token %}
  <div class="form-group">
    <div class="col-lg-5">
      <input type="text" name="srh" class="form-control" placeholder="Entre com Fornecedor ou Produto">
      <div>
        <label class="col-lg-2">
          <button type="submit" class="bnt bnt-danger">Search</button>
        </label>
      </div>
    </div>
  </div>
</form>
<hr>
<br>
<div>
  {% if messages %}
    <ul class="messages">
      {% for k in messages %}
      <li style="color: red">{{ k }}</li>
      {%  endfor %}
    </ul>
  {% endif %}
</div>
<br>
<div style="color: blue">
  {% if sr %}
    {% for k in sr %}
  <table border="0px" width="300px">
    <tr>
      <td>Fornecedor</td>
      <td>{{ k.fornecedor }}</td>
    </tr>
    <tr>
        <td>Produto</td>
        <td>{{ k.produto }}</td>
    </tr>
  </table>
{%  endfor %}
  {% endif %}
</div>


{% endblock conteudo %}